FROM python:3.11-slim
WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Запускаем консьюмера
CMD ["python", "run_consumer.py"]