FROM python:3.11-slim
WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Запускаем API без --reload (в Docker он не нужен)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]